# Plugins
source %sh{ echo "$HOME/.cache/kak-plugins/plug.kak/rc/plug.kak" }
set global plug_install_dir %sh{ echo "$HOME/.cache/kak-plugins" }
plug "andreyorst/plug.kak" noload
plug 'delapouite/kakoune-palette'
plug "lenormf/kakoune-extra" load %{
	git.kak
	pkgbuild.kak
}
plug "Delapouite/kakoune-buffers" config %{
	hook global WinDisplay .* info-buffers
	map global user b ':enter-user-mode buffers<ret>' -docstring 'buffers'
	map global buffers P ':pick-buffers<ret><esc>:enter-user-mode -lock pick-buffers<ret>' -docstring 'locked pick-buffers mode'
	
	alias global bd delete-buffer
	alias global bi info-buffers
}
plug "occivink/kakoune-gdb" config %{
	set global gdb_location_symbol ">"
	hook global WinSetOption filetype=rust %{
		set buffer gdb_program "rust-gdb"
	}
}
plug "ul/kak-lsp" noload do %{
	cargo build --release --locked
	cargo install --path . --force
} config %{
	map global user l -docstring 'load lsp' ':lsp-load<ret>'
	
	# have to declare it here, so that the modeline sees it
	decl -hidden str lsp_progress ""
	def lsp-load -hidden %{
		eval %sh{ kak-lsp --kakoune -s $kak_session }
		lsp-enable
		lsp-start
		
		map global user l ':enter-user-mode lsp<ret>' -docstring 'lsp'
		map global lsp  R ':lsp-stop<ret>:lsp-start<ret>' -docstring 'restart lsp'
		
		unmap global goto d
		unmap global goto r
		
		lsp-auto-hover-enable
		
		set global lsp_hover_anchor true
		set global lsp_insert_spaces false
		set global lsp_auto_highlight_references true
		set global lsp_hover_max_lines 1
		
		hook global KakEnd .* lsp-exit
		
		# copied from gh/ul/kak-lsp/wiki/Handling-progress-notifications
		def -hidden -params 4 -override lsp-handle-progress %{
			set global lsp_progress %sh{
				if test -n "$4"; then
					echo "[done]"
				else
					echo \[$1${2:+" $2"}${3:+" $3%"}\]
				fi
			}
		}
	}
}
plug "TeddyDD/kakoune-lf" config %{
	map global user f ':lf<ret>' -docstring 'file manager'
	
	set global lf_follow true
	set global lf_openables 'text/.*' 'application/json' 'inode/x-empty'
}
plug "occivink/kakoune-sudo-write" config %{
	def sudo-write-quit -docstring 'Write using sudo then quit' %{
		sudo-write
		quit
	}
	alias global sw  sudo-write
	alias global swq sudo-write-quit
}

source %sh{ echo "$kak_config/colorscheme.kak" }

# shell-like <control-direction> word-selection
map global insert <c-left> '<a-;>b' 
map global insert <c-right> '<a-;>w'

# same in normal mode
map global normal <c-left> 'b' 
map global normal <c-right> 'w'

# number lines
addhl global/ number-lines -hlcursor -min-digits 3

# highlight tabs
addhl global/ show-whitespaces -lf ' ' -spc ' ' -nbsp ' ' -tab '⠅'
addhl global/ show-matching

# highlight TODO, NOTE, and BUG keywords
# Not sure how to restrict the highlighting to a comment context,
#   but I don't tend to use uppercase NOTE for variable names anyway
addhl global/ regex \b(TODO|NOTE|BUG|ERROR)\b 0:default+rb

# Bye-bye clippy
set global ui_options ncurses_assistant=off

# Added current line index to modeline
set global modelinefmt '%opt{lsp_progress} %val{bufname} %val{cursor_line},%val{cursor_char_column} %val{buf_line_count} {{context_info}} {{mode_info}} %val{client}@[%val{session}]'

# Set tab length
set global tabstop 4

# Align cursors with spaces
set global aligntab false

# Remove *-trim-indent hooks
hook global WinSetOption filetype=.* %{
	remove-hooks window \w+-trim-indent
}

# Lint on write
hook global BufWritePost .* %{ eval %sh{
	if [ -n "$kak_opt_lintcmd" ]; then
		echo 'lint'
	fi
}}


# Shell linting
hook global WinSetOption filetype=(bash|sh|dash) %{
	set buffer lintcmd "shellcheck -f gcc"
	lint-enable
}

# Copy to clipboard
hook global NormalKey y %{ nop %sh{
	printf %s "$kak_main_reg_dquote" | xsel -ib
}}

# Paste from clipboard
map global normal P '!xsel -ob<ret>'
map global normal p '<a-!>xsel -ob<ret>'

# Comment and uncomment
map global normal '#' ':comment-line<ret>' -docstring 'comment line'
map global normal '<a-#>' ':comment-block<ret>' -docstring 'comment block'

# Set indent char to tab
set global indentwidth 0
set global scrolloff 4,4
