#!/bin/sh

echo 1

export _JAVA_AWT_WM_NONREPARENTING=1
export SXHKD_SHELL='/bin/sh'

export DT_PRI='I II III IV V VI VII VIII IX X'
export DT_SEC='1 2 3 4 5 6 7 8 9 10'

mon_pri="$(mons  | grep '[0-9]:' | grep '\*' | awk '{print $2}')"
bspc monitor $mon_pri -d $DT_PRI $DT_SEC

bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle             true
bspc config pointer_follows_monitor    true
bspc config window_gap                 4
bspc config border_width               2
bspc config split_ratio                0.5
bspc config automatic_scheme           longest_side
bspc config initial_polarity           first_child

$HOME/.bin/desktop/reload

# theming done in desktop/reload

bspc rule -a Sxiv       state=floating
bspc rule -a Gimp       state=floating
bspc rule -a Peek       state=floating
bspc rule -a zoom       state=floating

echo 1d
