#!/bin/sh

export DT_PRI='I II III IV V VI VII VIII IX X'
export DT_SEC='1 2 3 4 5 6 7 8 9 10'

mon_pri="$(mons  | grep '[0-9]:' | grep '\*' | awk '{print \$2}')"

bspc monitor $mon_pri -d $DT_PRI $DT_SEC

bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle             true
bspc config pointer_follows_monitor    true
bspc config window_gap                 4
bspc config border_width               2
bspc config split_ratio                0.5
bspc config external_rules_command     $HOME/.bin/desktop/rules

$HOME/.bin/desktop/reload

# Get colors
. $HOME/.theme/source

bspc config presel_feedback_color   $CL_BLACK_LT
bspc config normal_border_color     $CL_BLACK_DK
bspc config focused_border_color    $CL_WHITE_DK
bspc config active_border_color     $CL_BLACK_LT

bspc rule -a Sxiv     state=floating
bspc rule -a Gimp     state=floating
bspc rule -a Peek     state=floating
bspc rule -a zoom     state=floating

synclient TapButton1=1
