#!/bin/sh -u
# updates monitor configuration

DT_PRI='I II III IV V VI VII VIII IX X'
DT_SEC='1 2 3 4 5 6 7 8 9 10'
DT_ALL="$DT_PRI $DT_SEC"

mons=$(mons)
mon_mode="$(echo "$mons" | grep 'Mode: ' | awk '{print $2}')"
mon_pri="$(echo "$mons"  | grep '[0-9]:' | grep    '\*' | awk '{print $2}')"
mon_sec="$(echo "$mons"  | grep '[0-9]:' | grep -v '\*' | awk '{print $2}')"

if [ "$mon_mode" = 'extend' ]; then
	# Two monitors mode
	printf '%s' "$DT_PRI" | xargs -d ' ' -I '{}' bspc desktop '{}' -m $mon_pri
	printf '%s' "$DT_SEC" | xargs -d ' ' -I '{}' bspc desktop '{}' -m $mon_sec
	# try deleting 'Desktop' if it exists
	bspc desktop Desktop -r >/dev/null
	bspc monitor $mon_pri -o $DT_PRI
	bspc monitor $mon_sec -o $DT_SEC
else
	# Add dummy 'Desktop' to SEC
	# bspwn doesn't allow a monitor without a desktop
	[ -z "$mon_sec" ] && mon_sec="$(bspc query -M --names | grep -v $mon_pri)"
	if [ -n "$mon_sec" ] && bspc query -M -m $mon_sec >/dev/null; then
		bspc query -D -d Desktop >/dev/null || bspc monitor $mon_sec -a Desktop
		bspc desktop Desktop -m $mon_sec
	fi
	# Move all known desktops to PRI
	printf "%s" "$DT_ALL" | xargs -d ' ' -I '{}' bspc desktop '{}' -m $mon_pri
	bspc monitor $mon_pri -o $DT_ALL
fi
