#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

# Reload theme
. $HOME/.theme/source

# Set cursor
xsetroot -cursor_name $THEME_CURSOR

# Set wallpaper
xwallpaper --zoom ".walls/$THEME_WALL"

# Restart desktop daemons
killall mond mons picom sxhkd syndaemon redshift

redshift &
mond &
mons -a &
picom --config ~/.config/compton.conf &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
syndaemon &

synclient TouchpadOff=0
synclient PalmDetect=1

$HOME/.bin/desktop/reload-polybar
