#!/bin/sh

cd ~
unset FISH_TOP

monu

# reload theme
. $HOME/.theme/source

bspc config presel_feedback_color   $CL_BLACK_LT
bspc config normal_border_color     $CL_BLACK_DK
bspc config focused_border_color    $CL_WHITE_DK
bspc config active_border_color     $CL_BLACK_LT

xsetroot -cursor_name $THEME_CURSOR
xwallpaper --zoom ".walls/$THEME_WALL"

reload-daemons
reload-polybar
