#!/bin/sh

JAVA="/usr/lib/jvm/java-18-openjdk/bin/java"
JDTLS_CONFIG="$HOME/.config/jdtls/config_linux"
JDTLS_JAR="/usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar"
DATA_DIR="$HOME/.cache/jdtls/$PWD"

[ -d "$DATA_DIR" ] || mkdir -p "$DATA_DIR"

exec $JAVA \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.protocol=true \
    -Dlog.level=ALL \
    -Xms1g \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    -jar "$JDTLS_JAR" \
    -configuration "$JDTLS_CONFIG" \
    -data "$DATA_DIR"
