#!/bin/bash
MAC=false
date -r "$now" +%Y-%m-%d &> /dev/null
if [ "$?" -ne "0" ]; then echo "LINUX"; MAC=false; else echo 'MAC'; MAC=true; fi

now=`date +%s`

while true
do
  if [ "$MAC" == "true" ]; then data=`date -r "$now" +%Y-%m-%d`; else data=`date -d @"$now" +%Y-%m-%d`; fi
  echo -n "$data "
  str=`curl -s https://static.rust-lang.org/dist/$data/channel-rust-nightly.toml | grep -A1 rls-preview | grep -E 'version = "1.*"'`
  if [ "$str" != "" ]; then echo "yes"; else echo "no"; fi
  now=$(($now-86400))
done
