#!/bin/sh

cd /var/mega/
source ~/.config/mega.credentials

export MEGA_EMAIL MEGA_PWD

megasimplesync ~/Books     /Books     &
megasimplesync ~/Documents /Documents &
megasimplesync ~/Pictures  /Pictures  &
megasimplesync ~/Zenye     /Zenye     &
