#!/bin/sh
qemu-system-x86_64 -enable-kvm -m 3G -cpu host -vga virtio \
             -device virtio-tablet,wheel-axis=true \
             -smp 4,sockets=1,cores=4,threads=1 \
             -drive file=/usr/share/ovmf/x64/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
             -drive file=$HOME/.win/OVMF_VARS.fd,if=pflash,format=raw,unit=1 \
             -drive file=/dev/nvme0n1,format=raw
