#! /bin/sh

FILE="$1"
MIME="$(file --mime-type -bL "$FILE")"
EXT="${FILE#/*/*.}"
[ -t 1 ] && TTY='yes' || TTY='no'

orphan() {
	{ "$@" & } &
}

# Handle links
case "$(echo "$FILE" | cut -d: -f1)" in
	magnet) orphan tremc-notify "$FILE"; exit ;;
esac

# Handle mimetype
case "$MIME" in
	image/*)
		id_cur=1
		id=
		files=
		for f in "$(dirname "$FILE")"/*; do
			if file -b --mime-type "$f" | grep -q 'image'; then
				[ "$f" = "$FILE" ] && id=$id_cur
				id_cur=$((id_cur + 1))
				files="$(printf "%s\n%s" "$files" "$f")"
			fi
		done
		echo "$files" | orphan sxiv -a -i -n $id
		exit ;;
	
	application/pdf)
		orphan zathura "$FILE"
		exit ;;
	
	
esac

# Handle externsion
case "$EXT" in
esac

# Open every txt file in EDITOR
# I might need to open a txt file in another app, but I don't right now
if [ "$(file -bL --mime-encoding "$FILE")" != 'binary' ] && [ "$TTY" = yes ]; then
	$EDITOR "$FILE"
	exit
fi

orphan /usr/bin/xdg-open "${FILE}"
