#!/bin/sh
# adds files using glob patterns to yadm repo

yadm add .bin
yadm add .Xresources
yadm add .cargo/.crates.toml
yadm add .gitconfig
yadm add .irssi/config
yadm add .local/share/QuiteRss/QuiteRss/feeds.db
yadm add .newsboat/urls
yadm add .paclist
yadm add .rustup/settings.toml
yadm add .terminfo
yadm add .theme
yadm add .tmux.conf
yadm add .todo.md
yadm add .readme.md
yadm add .walls
yadm add .xinitrc
yadm add .config/{DIR_COLORS,alacritty,dunst,fish,fontconfig,gitui,gtk*,helix,htop,kak{,-lsp},lapce/*.toml,lf,mimeapps.list,mpd,ncmpcpp,picom.conf,polybar,rustfmt,sxhkd,systemd,tremc,yadm,yay,zathura}
