#!/bin/sh
# adds files using glob patterns to yadm repo

# export package list
pacman -Qqen > ./config/yadm/arch
pacman -Qqem > ./config/yadm/aur

yadm encrypt
yadm add .local/share/yadm/archive
yadm add .bin
yadm add .Xresources
yadm add .cargo/.crates.toml
yadm add .gitconfig
yadm add .irssi/config
yadm add .newsboat/urls
yadm add .paclist
yadm add .rustup/settings.toml
yadm add .terminfo
yadm add .theme
yadm add .tmux.conf
yadm add .todo.md
yadm add .readme.md
yadm add .walls
yadm add .xinitrc
yadm add .config/{DIR_COLORS,alacritty,dunst,fish,fontconfig,gitui,gtk*,helix,htop,hypr,kak{,-lsp},kickoff,lapce*.toml,lf,libresprite/palettes,lite-xl,nwg*,mimeapps.list,mpd,ncmpcpp,picom.conf,polybar,rustfmt,river,swappy,sxhkd,systemd,tremc,yadm,yay,tofi,waybar,zathura,bspwm,calibre,compton}
yadm commit -m $(date +%s)
