[v1]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-expand 1.0.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-profiler 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-profiler"]
"cargo-tree 0.29.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 11.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-watch 8.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"feroxbuster 2.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["feroxbuster"]
"flamegraph 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"ftw 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["ftw"]
"helix-term 0.6.0 (path+file:///mnt/data/Downloads/helix-22.03-source.tar/helix-term)" = ["hx"]
"kak-lsp 10.0.0-snapshot (path+file:///home/morga/.cache/kak-plugins/kak-lsp)" = ["kak-lsp"]
"miniserve 0.23.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["miniserve"]
"rusty-man 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-man"]
"rx 0.4.0 (git+https://github.com/cloudhead/rx?tag=v0.4.0#4235af8559d70b6a09a952932abda63362c4ff51)" = ["rx"]
"sqlx-cli 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"vimv 1.7.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["vimv"]
