[v1]
"cargo-expand 1.0.95 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-watch 8.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"dioxus-cli 0.5.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["dx"]
"flamegraph 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"sea-orm-cli 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "sea",
    "sea-orm-cli",
]
"sqlx-cli 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
