#!/bin/sh

# pass some env vars to systemd
systemctl --user import-environment PATH DISPLAY XAUTHORITY DBUS_SESSION_BUS_ADDRESS LS_COLORS SXHKD_SHELL _JAVA_AWT_WM_NONREPARENTING _JAVA_OPTIONS \
  TERMINAL BROWSER EDITOR VISUAL PAGER OPENER

# trigger graphical.target
systemctl --user --no-block start xsession.target

# export _JAVA_AWT_WM_NONREPARENTING=1
# export SXHKD_SHELL='/bin/sh' moved to xinitrc

export DT_PRI='I II III IV V VI VII VIII IX X'
export DT_SEC='1 2 3 4 5 6 7 8 9 10'

mon_pri="$(mons  | grep '[0-9]:' | grep '\*' | awk '{print $2}')"
bspc monitor $mon_pri -d $DT_PRI $DT_SEC

bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle             true
bspc config pointer_follows_monitor    true
bspc config window_gap                 4
bspc config border_width               2
bspc config split_ratio                0.5
bspc config automatic_scheme           longest_side
bspc config initial_polarity           first_child

$HOME/.bin/desktop/reload

bspc rule -a Sxiv       state=floating
bspc rule -a Gimp       state=floating
bspc rule -a Peek       state=floating
bspc rule -a zoom       state=floating
