#! /bin/bash

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X 1 2 3 4 5 6 7 8 9 10

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config pointer_follows_monitor true
bspc config window_gap              4
bspc config split_ratio             0.5
bspc config external_rules_command  $HOME/.config/bspwm/rules

$HOME/.config/bspwm/reload

source ~/.config/polybar/color

bspc config presel_feedback_color   $CL_BLACK_LT
bspc config normal_border_color     $CL_BLACK_DK
bspc config focused_border_color    $CL_WHITE_DK
bspc config active_border_color     $CL_BLACK_LT

bspc rule -a Aseprite state=floating
bspc rule -a Sxiv     state=floating
bspc rule -a Gimp     state=floating

# We don't care about it being restarted on reloads
syndaemon &
synclient TapButton1=1
