#! /bin/bash

source `dirname $0`/color

bspc subscribe | while read line; do
	D="$(bspc query -D -d $MON:focused --names)"
	echo -n "%{u$CL_WHITE_LT}%{-u}"
	for d in $(bspc query -D -m $MON --names); do
		dk=" $d "
		
		[ $d = "$D" ]                   &&\
			 dk="%{+u}$dk%{-u}"            # If focused, change underline
		[ -n "$(bspc query -N -d $d)" ] &&\
			 dk="%{B$CL_BLACK_DK}$dk%{B-}" # If occupied, change bg
		[ "$dk" = " $d " ]               &&\
			 dk=""
		echo -n "$dk"
	done
	
	line="$(echo "$line" | grep -Eo "$MON(:[^mM][^:]*)*")"
	lo="$(echo "$line" | grep -Eo 'L[TM]')"
	st="$(echo "$line" | grep -Eo 'T[TPF=@]')"
	if [ "$(bspc query -N -d focused | wc -l)" -gt 0 ]; then
		printf " %s%s" ${lo:1:1} ${st:1:1}
	fi
	echo "%{u-}"
done
