#! /bin/bash

# source $HOME/.theme/source

# bl

# ICON=
# echo /run/user/1000/bl | entr -n 'bl' |
# while read -r bl; do
# 	echo "%{F$CL_YELLOW_DK}$ICON%{F-} $bl%"
# done
# ICON=

# make sure /run/user/1000/bl exists
bl

echo "$XDG_RUNTIME_DIR/bl" | entr -n "$HOME/.bin/desktop/bl" |
while read -r bl; do
	echo "$bl%"
done
