#! /bin/bash

source $HOME/.theme/source

ICON_DISC=
ICON=
bluetoothctl --monitor | grep --line-buffered CHG |
while read -r line; do
	if bluetoothctl show | grep -q 'Powered: yes'; then
		echo -n "%{F$CL_GREEN_DK}$ICON%{F-}"
	else
		echo -n "%{F$CL_RED_DK}$ICON%{F-}"
	fi
	
	bluez="$(bluetoothctl info)"
	if test "$bluez" = "Missing device address argument"; then
		:
	else
		name="$(echo "$bluez" | grep 'Name' | awk '{print $2}')"
		echo -n " [$name]"
	fi
	echo
done
