#! /bin/bash

source $HOME/.theme/source

# Eventless sleep-loop
# Couldn't get bluetoothctl to export events to a pipe
ICON=
while :; do
	bluez="$(bluetoothctl -- info)"
	if test "$bluez" = "Missing device address argument"; then
		echo "%{F$CL_RED_DK}$ICON%{F-}"
	else
		name="$(echo "$bluez" | grep 'Name' | awk '{print $2}')"
		echo "%{F$CL_GREEN_DK}$ICON%{F-} [$name]"
	fi
	
	sleep 5
done
