#! /bin/bash

source $HOME/.theme/source

bspc subscribe |
while read -r line; do
	D="$(bspc query -D -d $MON:focused --names)"
	echo -n "%{u$CL_WHITE_LT}%{-u}"
	for d in $(bspc query -D -m $MON --names); do
		dk=" $d "
		
		[ $d = "$D" ]                   &&\
			 dk="%{+u}$dk%{-u}"            # If focused, change underline
		[ -n "$(bspc query -N -d $d)" ] &&\
			 dk="%{B$CL_BLACK_DK}$dk%{B-}" # If occupied, change bg
		[ "$dk" = " $d " ]               &&\
			 dk=""
		echo -n "$dk"
	done
	
	line="$(echo "$line" | grep -Eo "$MON(:[^mM][^:]*)*")"
	nodes="$(bspc query -N -d $MON:focused -n .leaf)"
	node_c="$(echo "$nodes" | wc -l)"
	if [ "$node_c" -ge 1 ]; then
		lo="$(echo "$line" | grep -Eo 'L[TM]')"
		st="$(echo "$line" | grep -Eo 'T[TPF=@]')"
		printf " %s%s" "${lo:1:1}" "${st:1:1}"
	fi
	if [ "$node_c" -ge 2 ]; then
		node_id="$(bspc query -N -d $MON:focused -n .active)"
		node_idx="$(echo "$nodes" | awk -v node_id="$node_id" '$1==node_id { print NR }')"
		printf "[%s/%s]" "$node_idx" "$node_c"
	fi
	echo "%{u-}"
done
