#! /bin/bash

ICON_UP=
ICON_DOWN=
ICON_OFF=
ICON_MUTE=
pactl subscribe | grep --line-buffered 'sink' |
while :; do
	# vol="$(pactl get-sink-volume @DEFAULT_SINK@ | head -n1 | awk '{print $5}' | cut -d% -f1)"
	vol=`pulsemixer --get-volume | awk '{print $1}'`
	[ "$(pulsemixer --get-mute)" = '1' ] && icon="$ICON_MUTE" || icon="$ICON_UP"
	printf " %s%%\n" "$icon $(pulsemixer --get-volume | awk '{print $1}')"
	
	read -r line
	sleep 0.2
done
