theme = "onedark"

[editor]
mouse = false
color-modes = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace]
# render = { space = "none", tab = "all", newline = "none" }
render = "none"

[editor.indent-guides]
render = true
character = "╎"
# character = "│"

[keys.normal]
# swap yanking and non-yanking delete and change
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"
