theme = "onedark"

[editor]
mouse = false
color-modes = true
rulers = [80, 120, 160]
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
# swap yanking and non-yanking delete and change
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"

[keys.normal.space]
# join and yank to clipboard
y = ":clipboard-yank-join"
